<?php
declare(strict_types=1);

/**
 * This source file is available under the terms of the
 * Pimcore Open Core License (POCL)
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 *  @copyright  Copyright (c) Pimcore GmbH (https://www.pimcore.com)
 *  @license    Pimcore Open Core License (POCL)
 */

namespace Pimcore\Bundle\StudioBackendBundle\OpenApi\Config;

use OpenApi\Attributes\Info;
use OpenApi\Attributes\License;
use OpenApi\Attributes\OpenApi;
use OpenApi\Attributes\Server;

/**
 * @internal
 * This class exists to document the public api
 */
#[Info(
    version: '0.10.21',
    description: 'API for Studio generated by OpenApi Generator via zircote/swagger-php',
    title: 'Studio Backend API'
)]

#[OpenApi(
    openapi: '3.1.0'
)]

#[License(
    name: 'Pimcore Open Core License (POCL)',
    url: 'https://github.com/pimcore/pimcore/blob/12.x/LICENSE.md'
)]

#[Server(
    url: '/',
    description: 'Pimcore Studio Backend API'
)]

final class Spec
{
    private function __construct()
    {
    }
}
