version: '3.0'
services:
    php-studio-backend-bundle:
        image: pimcore/pimcore:php8.4-debug-latest
        environment:
            PHP_IDE_CONFIG: serverName=localhost
        working_dir: /var/cli
        volumes:
            - .:/var/cli/
            - ./.docker/30-xdebug.ini:/usr/local/etc/php/conf.d/30-xdebug.ini