Pimcore\Bundle\StudioApiBundle\Dto\Asset\Image:
    attributes:
        thumbnail:
            groups: ['image:read', 'asset:read', 'image:write']
        dimensions:
            groups: ['image:read', 'asset:read', 'image:write']
        width:
            groups: ['image:read', 'asset:read', 'image:write']
        height:
            groups: ['image:read', 'asset:read', 'image:write']
#        lowQualityPreviewDataUri:
#            groups: ['image:read']
#        lowQualityPreviewPath:
#            groups: ['image:read']
#        iPTCData:
#            groups: ['image:read']
#        xMPData:
#            groups: ['image:read']
