Pimcore\Bundle\StudioApiBundle\Dto\Asset\MetaData:
    attributes:
        name:
            groups: [ 'asset:read' ]
        language:
            groups: [ 'asset:read' ]
        type:
            groups: [ 'asset:read' ]
        data:
            groups: [ 'asset:read' ]
