framework:
  rate_limiter:
    studio_api_general:
      policy: 'sliding_window'
      limit: 500
      interval: '1 minute'
    reset_password:
      policy: 'fixed_window'
      limit: 5
      interval: '5 minutes'
    setting_admin_thumbnail:
      policy: 'fixed_window'
      limit: 60
      interval: '1 minutes'
