resources:
    Pimcore\Bundle\StudioApiBundle\Dto\Asset:
        security: 'is_granted("API_PLATFORM")'
        operations:
            ApiPlatform\Metadata\GetCollection:
                filters:
                    - Pimcore\Bundle\StudioApiBundle\Filter\AssetParentIdFilter
                    - Pimcore\Bundle\StudioApiBundle\Filter\AssetIdSearchFilter
                    - Pimcore\Bundle\StudioApiBundle\Filter\AssetExcludeFolderFilter
                    - Pimcore\Bundle\StudioApiBundle\Filter\AssetPathFilter
                paginationClientItemsPerPage: true
            ApiPlatform\Metadata\Get:
                normalizationContext:
                    groups: [ 'asset:read', 'asset:item:get', 'dependency:read', 'property:read', 'element:read', 'element:item:get']
            ApiPlatform\Metadata\Put:
            ApiPlatform\Metadata\Post:
            ApiPlatform\Metadata\Delete:
            ApiPlatform\Metadata\Patch:
        provider: Pimcore\Bundle\StudioApiBundle\State\AssetProvider
        normalizationContext:
            groups: ['asset:read', 'dependency:read', 'property:read', 'element:read']
        denormalizationContext:
            groups: ['asset:write']
        properties:
            id:
                identifier: true

properties:
    Pimcore\Bundle\StudioApiBundle\Dto\Asset:
        dependencies:
            genId: false