<?php

namespace Pimcore\Bundle\StudioApiBundle\Config\OpenApi;

use OpenApi\Attributes\Info;
use OpenApi\Attributes\License;
use OpenApi\Attributes\SecurityScheme;

#[Info(
    version: 'v1',
    description: 'Rest API for Studio generated by OpenAPI Generator via zircote/swagger-php',
    title: 'Studio API'
)]
#[License(name: 'MIT', identifier: 'MIT')]
final class Spec
{

}