Pimcore\Bundle\StudioApiBundle\Dto\Asset:
    attributes:
        type:
            groups: ['asset:read']
        iconName:
            groups: [ 'asset:read' ]
        children:
            groups: ['asset:read']
        filename:
            groups: ['asset:read', 'asset:write']
        mimetype:
            groups: ['asset:read']
        metadata:
            groups: ['asset:read']
        customSettings:
            groups: ['asset:item:get']
        hasMetaData:
            groups: ['asset:read']
        userPermissions:
            groups: ['asset:read']
