Pimcore\Bundle\StudioApiBundle\Dto\Dependency:
    attributes:
        sourceId:
            groups: ['dependency:read']
        sourceType:
            groups: ['dependency:read']
        required:
            groups: ['dependency:read']
        requiredByTotalCount:
            groups: ['dependency:read']
        requiresTotalCount:
            groups: ['dependency:read']
        requires:
            groups: ['dependency:read']
        requiredBy:
            groups: ['dependency:read']