Pimcore\Bundle\StudioApiBundle\Dto\Element:
    attributes:
        id:
            groups: ['element:read', 'element:write']
        parentId:
            groups: ['element:read', 'element:write']
        permissions:
            groups: ['element:read']
        path:
            groups: ['element:read']
        creationDate:
            groups: ['element:read']
        modificationDate:
            groups: ['element:read']
        userOwner:
            groups: ['element:read']
        userModification:
            groups: ['element:read']
        properties:
            groups: ['element:item:get']
        versions:
            groups: ['element:read']
        locked:
            groups: ['element:read']
        lock:
            groups: ['element:read']
        dependencies:
            groups: ['element:item:get']
        scheduledTasks:
            groups: ['element:item:get']
        versionCount:
            groups: ['element:item:get']
        fullPath:
            groups: ['element:read']
        userPermissions:
            groups: ['element:read']
