Pimcore\Bundle\StudioApiBundle\Dto\Token\Output:
  attributes:
    token:
      groups: ['token:read']
    username:
      groups: [ 'token:read' ]
    lifetime:
      groups: ['token:read']
    validUntil:
      groups: ['token:read']
