resources:
    Pimcore\Bundle\StudioApiBundle\Dto\Asset\Image:
        provider: Pimcore\Bundle\StudioApiBundle\State\Asset\Provider
        processor: Pimcore\Bundle\StudioApiBundle\State\Asset\Processor
        operations:
            ApiPlatform\Metadata\Get:
                normalizationContext:
                    groups: ['image:read', 'asset:read', 'asset:item:get', 'dependency:read', 'property:read', 'element:read', 'element:item:get' ]
            ApiPlatform\Metadata\Patch:
        properties:
            id:
                identifier: true
        normalizationContext:
            groups: ['image:read', 'asset:read', 'dependency:read', 'property:read', 'element:read']
        denormalizationContext:
            groups: ['image:write', 'asset:write', 'element:write']
