resources:
    Pimcore\Bundle\StudioApiBundle\Dto\Token\Create:
        shortName: Token-Create
        operations:
            ApiPlatform\Metadata\Post:
                processor: Pimcore\Bundle\StudioApiBundle\State\Token\Create\Processor
                output: Pimcore\Bundle\StudioApiBundle\Dto\Token\Output
                uriTemplate: '/token/create'
                openapiContext:
                    summary: 'Creates and returns a token'

        normalizationContext:
          groups: [ 'token:read' ]