services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # controllers are imported separately to make sure they're public
  # and have a tag that allows actions to type-hint services
  Pimcore\Bundle\StudioBackendBundle\Asset\Controller\:
    resource: '../src/Asset/Controller'
    public: true
    tags: [ 'controller.service_arguments' ]

  # Hydrators
  Pimcore\Bundle\StudioBackendBundle\Asset\Hydrator\CustomSettingsHydratorInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Hydrator\CustomSettingsHydrator

  # Encoder
  Pimcore\Bundle\StudioBackendBundle\Asset\Encoder\TextEncoderInterface:
      class: Pimcore\Bundle\StudioBackendBundle\Asset\Encoder\TextEncoder

  Pimcore\Bundle\StudioBackendBundle\Asset\Service\AssetServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Service\AssetService