services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # controllers are imported separately to make sure they're public
  # and have a tag that allows actions to type-hint services
  Pimcore\Bundle\StudioBackendBundle\Asset\Controller\:
    resource: '../src/Asset/Controller'
    public: true
    tags: [ 'controller.service_arguments' ]

  # Hydrators
  Pimcore\Bundle\StudioBackendBundle\Asset\Hydrator\CustomSettingsHydratorInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Hydrator\CustomSettingsHydrator

  Pimcore\Bundle\StudioBackendBundle\Asset\Hydrator\CustomMetaDataHydratorInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Hydrator\CustomMetaDataHydrator

  # Encoder
  Pimcore\Bundle\StudioBackendBundle\Asset\Encoder\TextEncoderInterface:
      class: Pimcore\Bundle\StudioBackendBundle\Asset\Encoder\TextEncoder

  Pimcore\Bundle\StudioBackendBundle\Asset\Service\AssetServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Service\AssetService

  Pimcore\Bundle\StudioBackendBundle\Asset\Service\Data\CustomSettingsServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Service\Data\CustomSettingsService

  Pimcore\Bundle\StudioBackendBundle\Asset\Service\Data\CustomMetaDataServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Service\Data\CustomMetaDataService

  Pimcore\Bundle\StudioBackendBundle\Asset\Service\Data\TextServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Service\Data\TextService

  Pimcore\Bundle\StudioBackendBundle\Asset\Service\DownloadServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Service\DownloadService

  Pimcore\Bundle\StudioBackendBundle\Asset\Service\ThumbnailServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Service\ThumbnailService

  Pimcore\Bundle\StudioBackendBundle\Asset\Service\BinaryServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Service\BinaryService

  Pimcore\Bundle\StudioBackendBundle\Asset\Service\DocumentServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Service\DocumentService

  Pimcore\Bundle\StudioBackendBundle\Asset\Service\UploadServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Service\UploadService

  Pimcore\Bundle\StudioBackendBundle\Asset\Service\ExecutionEngine\CloneServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Service\ExecutionEngine\CloneService

  Pimcore\Bundle\StudioBackendBundle\Asset\Service\ExecutionEngine\ZipServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Service\ExecutionEngine\ZipService

  Pimcore\Bundle\StudioBackendBundle\Asset\Service\ExecutionEngine\CsvServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Service\ExecutionEngine\CsvService

  Pimcore\Bundle\StudioBackendBundle\Asset\Service\ExecutionEngine\DeleteServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Asset\Service\ExecutionEngine\DeleteService


  #
  # Updaters
  #

  Pimcore\Bundle\StudioBackendBundle\Asset\Updater\Adapter\ImageAdapter:
    tags: [ 'pimcore.studio_backend.update_adapter' ]

  Pimcore\Bundle\StudioBackendBundle\Asset\Updater\Adapter\CustomMetaDataAdapter:
    tags: [ 'pimcore.studio_backend.update_adapter' ]

  Pimcore\Bundle\StudioBackendBundle\Asset\Updater\Adapter\CustomSettingsAdapter:
    tags: [ 'pimcore.studio_backend.update_adapter' ]

  Pimcore\Bundle\StudioBackendBundle\Asset\Updater\Adapter\DataAdapter:
    tags: [ 'pimcore.studio_backend.update_adapter' ]

  #
  # Patcher
  #

  Pimcore\Bundle\StudioBackendBundle\Asset\Patcher\Adapter\MetaDataAdapter:
    tags: [ 'pimcore.studio_backend.patch_adapter' ]

  #
  # Handler
  #

  Pimcore\Bundle\StudioBackendBundle\Asset\ExecutionEngine\AutomationAction\Messenger\Handler\AssetCloneHandler: ~
  Pimcore\Bundle\StudioBackendBundle\Asset\ExecutionEngine\AutomationAction\Messenger\Handler\AssetDeleteHandler: ~
  Pimcore\Bundle\StudioBackendBundle\Asset\ExecutionEngine\AutomationAction\Messenger\Handler\AssetUploadHandler: ~
  Pimcore\Bundle\StudioBackendBundle\Asset\ExecutionEngine\AutomationAction\Messenger\Handler\CsvCreationHandler: ~
  Pimcore\Bundle\StudioBackendBundle\Asset\ExecutionEngine\AutomationAction\Messenger\Handler\CsvDataCollectionHandler: ~
  Pimcore\Bundle\StudioBackendBundle\Asset\ExecutionEngine\AutomationAction\Messenger\Handler\ZipDownloadHandler: ~
  Pimcore\Bundle\StudioBackendBundle\Asset\ExecutionEngine\AutomationAction\Messenger\Handler\ZipUploadHandler: ~

  #
  # Event Subscriber
  #

  Pimcore\Bundle\StudioBackendBundle\Asset\EventSubscriber\CloneSubscriber: ~
  Pimcore\Bundle\StudioBackendBundle\Asset\EventSubscriber\CsvCreationSubscriber: ~
  Pimcore\Bundle\StudioBackendBundle\Asset\EventSubscriber\DeletionSubscriber: ~
  Pimcore\Bundle\StudioBackendBundle\Asset\EventSubscriber\UploadSubscriber: ~
  Pimcore\Bundle\StudioBackendBundle\Asset\EventSubscriber\ZipDownloadSubscriber: ~
  Pimcore\Bundle\StudioBackendBundle\Asset\EventSubscriber\ZipUploadSubscriber: ~

  #
  # Mercure SSE
  #

  Pimcore\Bundle\StudioBackendBundle\Asset\Mercure\Provider\AssetTopicProvider:
    tags: [ 'pimcore.studio_backend.mercure.topic.provider' ]