services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Hydrators
  Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\ArchiveHydratorInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\ArchiveHydrator
  Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\AudioHydratorInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\AudioHydrator
  Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\DocumentHydratorInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\DocumentHydrator
  Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\FolderHydratorInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\FolderHydrator
  Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\ImageHydratorInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\ImageHydrator
  Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\TextHydratorInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\TextHydrator
  Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\UnknownHydratorInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\UnknownHydrator
  Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\VideoHydratorInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\VideoHydrator
  Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\MetaDataHydratorInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\MetaDataHydrator

  Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\AssetHydratorInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\AssetHydrator

  Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\PermissionsHydratorInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\PermissionsHydrator

  # Services
  Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\AssetHydratorServiceInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\AssetHydratorService
    arguments:
      $assetHydratorLocator: '@open_search.asset_hydrator.service_locator'


  # Assets
  Pimcore\Bundle\StudioApiBundle\DataIndex\AssetSearchServiceInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\AssetSearchService

  Pimcore\Bundle\StudioApiBundle\DataIndex\Adapter\AssetSearchAdapterInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\Adapter\AssetSearchAdapter

  Pimcore\Bundle\StudioApiBundle\DataIndex\Provider\AssetQueryProviderInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\Provider\AssetQueryProvider

  #Data Objects
  Pimcore\Bundle\StudioApiBundle\DataIndex\DataObjectSearchServiceInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\DataObjectSearchService

  Pimcore\Bundle\StudioApiBundle\DataIndex\Adapter\DataObjectSearchAdapterInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\Adapter\DataObjectSearchAdapter

  Pimcore\Bundle\StudioApiBundle\DataIndex\Provider\DataObjectQueryProviderInterface:
    class: Pimcore\Bundle\StudioApiBundle\DataIndex\Provider\DataObjectQueryProvider


  #Service Locator
  open_search.asset_hydrator.service_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: [ 'container.service_locator' ]
    arguments:
      - Pimcore\Bundle\GenericDataIndexBundle\Model\Search\Asset\SearchResult\SearchResultItem\Archive: '@Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\ArchiveHydratorInterface'
        Pimcore\Bundle\GenericDataIndexBundle\Model\Search\Asset\SearchResult\SearchResultItem\Audio: '@Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\AudioHydratorInterface'
        Pimcore\Bundle\GenericDataIndexBundle\Model\Search\Asset\SearchResult\SearchResultItem\Document: '@Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\DocumentHydratorInterface'
        Pimcore\Bundle\GenericDataIndexBundle\Model\Search\Asset\SearchResult\SearchResultItem\Folder: '@Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\FolderHydratorInterface'
        Pimcore\Bundle\GenericDataIndexBundle\Model\Search\Asset\SearchResult\SearchResultItem\Image: '@Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\ImageHydratorInterface'
        Pimcore\Bundle\GenericDataIndexBundle\Model\Search\Asset\SearchResult\SearchResultItem\Text: '@Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\TextHydratorInterface'
        Pimcore\Bundle\GenericDataIndexBundle\Model\Search\Asset\SearchResult\SearchResultItem\Unknown: '@Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\UnknownHydratorInterface'
        Pimcore\Bundle\GenericDataIndexBundle\Model\Search\Asset\SearchResult\SearchResultItem\Video: '@Pimcore\Bundle\StudioApiBundle\DataIndex\Hydrator\Asset\VideoHydratorInterface'