services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  #Filter

  #Common
  Pimcore\Bundle\StudioApiBundle\Service\Filter\FilterLoaderInterface:
    class: Pimcore\Bundle\StudioApiBundle\Service\Filter\Loader\TaggedIteratorAdapter

  Pimcore\Bundle\StudioApiBundle\Service\Filter\FilterServiceInterface:
    class: Pimcore\Bundle\StudioApiBundle\Service\Filter\FilterService

  Pimcore\Bundle\StudioApiBundle\Filter\PageFilter:
    tags: [ 'pimcore.studio_api.filter' ]

  Pimcore\Bundle\StudioApiBundle\Filter\PageSizeFilter:
    tags: [ 'pimcore.studio_api.filter' ]

  Pimcore\Bundle\StudioApiBundle\Filter\ExcludeFolderFilter:
    tags: [ 'pimcore.studio_api.filter' ]

  Pimcore\Bundle\StudioApiBundle\Filter\IdSearchFilter:
    tags: [ 'pimcore.studio_api.filter' ]

  Pimcore\Bundle\StudioApiBundle\Filter\ParentIdFilter:
    tags: [ 'pimcore.studio_api.filter' ]

  Pimcore\Bundle\StudioApiBundle\Filter\PathFilter:
    tags: [ 'pimcore.studio_api.filter' ]

  # DataObject
  Pimcore\Bundle\StudioApiBundle\Filter\DataObject\ClassIdFilter:
      tags: [ 'pimcore.studio_api.data_object.filter' ]