services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false


  Pimcore\Bundle\StudioBackendBundle\DataIndex\Grid\GridSearchInterface:
    class: Pimcore\Bundle\StudioBackendBundle\DataIndex\Grid\GridSearch


  Pimcore\Bundle\StudioBackendBundle\Grid\Mapper\ColumnMapperInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Grid\Mapper\ColumnMapper

  Pimcore\Bundle\StudioBackendBundle\Grid\Service\GridServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Grid\Service\GridService

  Pimcore\Bundle\StudioBackendBundle\Grid\Service\ConfigurationServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Grid\Service\ConfigurationService

  Pimcore\Bundle\StudioBackendBundle\Grid\Service\SystemColumnServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Grid\Service\SystemColumnService

  Pimcore\Bundle\StudioBackendBundle\Grid\Service\ColumnDefinitionLoaderInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Grid\Service\Loader\TaggedIteratorColumnDefinitionLoader

  Pimcore\Bundle\StudioBackendBundle\Grid\Service\ColumnResolverLoaderInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Grid\Service\Loader\TaggedIteratorColumnResolverLoader

  Pimcore\Bundle\StudioBackendBundle\Grid\Service\ColumnCollectorLoaderInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Grid\Service\Loader\TaggedIteratorColumnCollectorLoader

  #
  # Column Definitions
  #

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Definition\System\IntegerDefinition:
    tags: [ 'pimcore.studio_backend.grid_column_definition' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Definition\System\StringDefinition:
    tags: [ 'pimcore.studio_backend.grid_column_definition' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Definition\System\DatetimeDefinition:
    tags: [ 'pimcore.studio_backend.grid_column_definition' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Definition\System\ImageDefinition:
    tags: [ 'pimcore.studio_backend.grid_column_definition' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Definition\System\FileSizeDefinition:
    tags: [ 'pimcore.studio_backend.grid_column_definition' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Definition\MetaData\SelectDefinition:
    tags: [ 'pimcore.studio_backend.grid_column_definition' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Definition\MetaData\InputDefinition:
    tags: [ 'pimcore.studio_backend.grid_column_definition' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Definition\MetaData\TextareaDefinition:
    tags: [ 'pimcore.studio_backend.grid_column_definition' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Definition\MetaData\CheckboxDefinition:
    tags: [ 'pimcore.studio_backend.grid_column_definition' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Definition\MetaData\DateDefinition:
    tags: [ 'pimcore.studio_backend.grid_column_definition' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Definition\MetaData\AssetDefinition:
    tags: [ 'pimcore.studio_backend.grid_column_definition' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Definition\MetaData\DocumentDefinition:
    tags: [ 'pimcore.studio_backend.grid_column_definition' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Definition\MetaData\DataObjectDefinition:
    tags: [ 'pimcore.studio_backend.grid_column_definition' ]

  #
  # Column Resolver
  #

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Resolver\System\StringResolver:
    tags: [ 'pimcore.studio_backend.grid_column_resolver' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Resolver\System\IntegerResolver:
    tags: [ 'pimcore.studio_backend.grid_column_resolver' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Resolver\System\FileSizeResolver:
    tags: [ 'pimcore.studio_backend.grid_column_resolver' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Resolver\System\DatetimeResolver:
    tags: [ 'pimcore.studio_backend.grid_column_resolver' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Resolver\System\ImageResolver:
    tags: [ 'pimcore.studio_backend.grid_column_resolver' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Resolver\MetaData\SelectResolver:
    tags: [ 'pimcore.studio_backend.grid_column_resolver' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Resolver\MetaData\TextareaResolver:
    tags: [ 'pimcore.studio_backend.grid_column_resolver' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Resolver\MetaData\CheckboxResolver:
    tags: [ 'pimcore.studio_backend.grid_column_resolver' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Resolver\MetaData\DateResolver:
    tags: [ 'pimcore.studio_backend.grid_column_resolver' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Resolver\MetaData\AssetResolver:
    tags: [ 'pimcore.studio_backend.grid_column_resolver' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Resolver\MetaData\DocumentResolver:
    tags: [ 'pimcore.studio_backend.grid_column_resolver' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Resolver\MetaData\DataObjectResolver:
    tags: [ 'pimcore.studio_backend.grid_column_resolver' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Resolver\MetaData\InputResolver:
    tags: [ 'pimcore.studio_backend.grid_column_resolver' ]

  #
  # Column Collector
  #

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Collector\SystemFieldCollector:
    tags: [ 'pimcore.studio_backend.grid_column_collector' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Column\Collector\MetaDataCollector:
    tags: [ 'pimcore.studio_backend.grid_column_collector' ]