services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pimcore\Bundle\StudioBackendBundle\Grid\Mapper\ColumnMapperInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Grid\Mapper\ColumnMapper

  Pimcore\Bundle\StudioBackendBundle\Grid\Service\GridServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Grid\Service\GridService

  Pimcore\Bundle\StudioBackendBundle\Grid\Service\SystemColumnServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Grid\Service\SystemColumnService

  Pimcore\Bundle\StudioBackendBundle\Grid\Service\AdapterLoaderInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Grid\Service\Loader\TaggedIteratorAdapter

  #
  # Adapter
  #

  Pimcore\Bundle\StudioBackendBundle\Grid\Adapter\IntegerColumnAdapter:
    tags: [ 'pimcore.studio_backend.grid_column_adapter' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Adapter\StringColumnAdapter:
    tags: [ 'pimcore.studio_backend.grid_column_adapter' ]

  Pimcore\Bundle\StudioBackendBundle\Grid\Adapter\DatetimeColumnAdapter:
    tags: [ 'pimcore.studio_backend.grid_column_adapter' ]

