services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pimcore\Bundle\StudioBackendBundle\Patcher\Service\AdapterLoaderInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Patcher\Service\Loader\TaggedIteratorAdapter

  Pimcore\Bundle\StudioBackendBundle\Patcher\Service\PatchServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Patcher\Service\PatchService

  Pimcore\Bundle\StudioBackendBundle\Asset\Patcher\Adapter\MetadataAdapter:
    tags : ['pimcore.studio_backend.patch_adapter']