services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # controllers are imported separately to make sure they're public
  # and have a tag that allows actions to type-hint services
  Pimcore\Bundle\StudioBackendBundle\Perspective\Controller\:
    resource: '../src/Perspective/Controller'
    public: true
    tags: [ 'controller.service_arguments' ]

  #
  # Services
  #

  Pimcore\Bundle\StudioBackendBundle\Perspective\Service\Loader\Widget\ConfigRepositoryLoaderInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Perspective\Service\Loader\Widget\TaggedIteratorRepository

  Pimcore\Bundle\StudioBackendBundle\Perspective\Service\Loader\Widget\ConfigHydratorLoaderInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Perspective\Service\Loader\Widget\TaggedIteratorHydrator

  Pimcore\Bundle\StudioBackendBundle\Perspective\Service\WidgetServiceInterface:
      class: Pimcore\Bundle\StudioBackendBundle\Perspective\Service\WidgetService

  #
  # Hydrators
  #

  Pimcore\Bundle\StudioBackendBundle\Perspective\Hydrator\WidgetTypeHydratorInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Perspective\Hydrator\WidgetTypeHydrator

  Pimcore\Bundle\StudioBackendBundle\Perspective\Hydrator\ElementTreeWidgetConfigHydrator:
    tags: [ 'pimcore.studio_backend.widget_hydrator' ]

  #
  # Repositories
  #

  Pimcore\Bundle\StudioBackendBundle\Perspective\Repository\ElementTreeWidgetConfigRepository:
    tags: [ 'pimcore.studio_backend.widget_repository' ]




