services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # controllers are imported separately to make sure they're public
  # and have a tag that allows actions to type-hint services
  Pimcore\Bundle\StudioBackendBundle\Property\Controller\:
    resource: '../src/Property/Controller'
    public: true
    tags: [ 'controller.service_arguments' ]


  Pimcore\Bundle\StudioBackendBundle\Property\Repository\PropertyRepositoryInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Property\Repository\PropertyRepository

  Pimcore\Bundle\StudioBackendBundle\Property\Service\PropertyServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Property\Service\PropertyService

  Pimcore\Bundle\StudioBackendBundle\Property\Hydrator\PropertyHydratorInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Property\Hydrator\PropertyHydrator

  #
  # Filter
  #
  Pimcore\Bundle\StudioBackendBundle\Property\Filter\PropertyFilter:
    tags: [ 'pimcore.studio_backend.listing.filter' ]

