services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  #Factory

  Pimcore\Bundle\StudioBackendBundle\Provider\FilterServiceProviderInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Provider\FilterServiceProvider

  Pimcore\Bundle\StudioBackendBundle\Provider\FilterServiceLoaderInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Provider\Loader\TaggedIteratorAdapter
