services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #
    # INSTALLER
    #
    Pimcore\Bundle\StudioBackendBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('PimcoreStudioBackendBundle')"







