services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # controllers are imported separately to make sure they're public
  # and have a tag that allows actions to type-hint services
  Pimcore\Bundle\StudioBackendBundle\Thumbnail\Controller\:
    resource: '../src/Thumbnail/Controller'
    public: true
    tags: [ 'controller.service_arguments' ]

  #
  # Repositories
  #

  Pimcore\Bundle\StudioBackendBundle\Thumbnail\Repository\ThumbnailConfigRepositoryInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Thumbnail\Repository\ThumbnailConfigRepository

  Pimcore\Bundle\StudioBackendBundle\Thumbnail\Repository\ImageThumbnailRepositoryInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Thumbnail\Repository\ImageThumbnailRepository

  Pimcore\Bundle\StudioBackendBundle\Thumbnail\Repository\VideoThumbnailRepositoryInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Thumbnail\Repository\VideoThumbnailRepository

  #
  # Hydrators
  #

  Pimcore\Bundle\StudioBackendBundle\Thumbnail\Hydrator\ThumbnailConfigHydratorInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Thumbnail\Hydrator\ThumbnailConfigHydrator

  Pimcore\Bundle\StudioBackendBundle\Thumbnail\Hydrator\ThumbnailFolderHydratorInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Thumbnail\Hydrator\ThumbnailFolderHydrator

  Pimcore\Bundle\StudioBackendBundle\Thumbnail\Hydrator\Image\ConfigDetailHydratorInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Thumbnail\Hydrator\Image\ConfigDetailHydrator

  Pimcore\Bundle\StudioBackendBundle\Thumbnail\Hydrator\Video\ConfigDetailHydratorInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Thumbnail\Hydrator\Video\ConfigDetailHydrator

  #
  # Services
  #

  Pimcore\Bundle\StudioBackendBundle\Thumbnail\Service\ThumbnailConfigServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Thumbnail\Service\ThumbnailConfigService

  Pimcore\Bundle\StudioBackendBundle\Thumbnail\Service\ImageThumbnailServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Thumbnail\Service\ImageThumbnailService

  Pimcore\Bundle\StudioBackendBundle\Thumbnail\Service\VideoThumbnailServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\Thumbnail\Service\VideoThumbnailService

