services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # controllers are imported separately to make sure they're public
  # and have a tag that allows actions to type-hint services
  Pimcore\Bundle\StudioBackendBundle\User\Controller\:
    resource: '../src/User/Controller'
    public: true
    tags: [ 'controller.service_arguments' ]

  Pimcore\Bundle\StudioBackendBundle\User\RateLimiter\RateLimiterInterface:
    class: Pimcore\Bundle\StudioBackendBundle\User\RateLimiter\RateLimiter

  #
  # Services
  #
  Pimcore\Bundle\StudioBackendBundle\User\Service\UserServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\User\Service\UserService

  Pimcore\Bundle\StudioBackendBundle\User\Service\UserUpdateServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\User\Service\UserUpdateService

  Pimcore\Bundle\StudioBackendBundle\User\Service\UserFolderServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\User\Service\UserFolderService

  Pimcore\Bundle\StudioBackendBundle\User\Service\UserCloneServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\User\Service\UserCloneService

  Pimcore\Bundle\StudioBackendBundle\User\Service\UserPermissionServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\User\Service\UserPermissionService

  Pimcore\Bundle\StudioBackendBundle\User\Service\WorkspaceCloneServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\User\Service\WorkspaceCloneService

  Pimcore\Bundle\StudioBackendBundle\User\Service\RoleServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\User\Service\RoleService

  Pimcore\Bundle\StudioBackendBundle\User\Service\MailServiceInterface:
    class: Pimcore\Bundle\StudioBackendBundle\User\Service\MailService
    arguments: [ '@Pimcore\Bundle\StudioBackendBundle\Setting\Provider\SystemSettingsProvider' ]

  #
  # Hydrators
  #
  Pimcore\Bundle\StudioBackendBundle\User\Hydrator\UserTreeNodeHydratorInterface:
    class: Pimcore\Bundle\StudioBackendBundle\User\Hydrator\UserTreeNodeHydrator

  Pimcore\Bundle\StudioBackendBundle\User\Hydrator\PermissionHydratorInterface:
    class: Pimcore\Bundle\StudioBackendBundle\User\Hydrator\PermissionHydrator

  Pimcore\Bundle\StudioBackendBundle\User\Hydrator\UserHydratorInterface:
    class: Pimcore\Bundle\StudioBackendBundle\User\Hydrator\UserHydrator

  #
  # Repositories
  #
  Pimcore\Bundle\StudioBackendBundle\User\Repository\UserRepositoryInterface:
    class: Pimcore\Bundle\StudioBackendBundle\User\Repository\UserRepository

  Pimcore\Bundle\StudioBackendBundle\User\Repository\UserFolderRepositoryInterface:
    class: Pimcore\Bundle\StudioBackendBundle\User\Repository\UserFolderRepository

  Pimcore\Bundle\StudioBackendBundle\User\Repository\PermissionRepositoryInterface:
    class: Pimcore\Bundle\StudioBackendBundle\User\Repository\PermissionRepository

  Pimcore\Bundle\StudioBackendBundle\User\Repository\RoleRepositoryInterface:
    class: Pimcore\Bundle\StudioBackendBundle\User\Repository\RoleRepository