Token:
  type: object
  properties:
    token:
      type: string
      example: generated_token
    username:
      type: string
      example: admin
    lifetime:
      type: integer
      example: 3600