Unauthorized:
  description: Unauthorized
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
            example: 'Unauthorized'