imports:
    - { resource: security.yaml }
    - { resource: firewall.yaml }
    - { resource: execution_engine.yaml }
    - { resource: doctrine.yaml }

pimcore:
    translations:
        domains:
            - studio

pimcore_studio_backend:
    open_api_scan_paths:
        - "%kernel.project_dir%/vendor/pimcore/studio-backend-bundle/src"
    asset_default_formats:
        web:
            resize_mode: "scaleByWidth"
            width: 3500
            dpi: 72
            format: "JPEG"
            quality: 85
        print:
            resize_mode: "scaleByWidth"
            width: 6000
            dpi: 300
            format: "JPEG"
            quality: 95
        office:
            resize_mode: "scaleByWidth"
            width: 1190
            dpi: 144
            format: "JPEG"
            quality: 90
    element_recycle_bin_threshold: 100
    grid:
        asset:
            predefined_columns:
                - key: preview
                  group: system
                - key: id
                  group: system
                - key: type
                  group: system
                - key: fullpath
                  group: system
                - key: filename
                  group: system
                - key: creationDate
                  group: system
                - key: modificationDate
                  group: system
                - key: size
                  group: system
    notes:
        types:
            asset: ['content', 'seo', 'warning', 'notice']
            document: ['content', 'seo', 'warning', 'notice']
            data-object: ['content', 'seo', 'warning', 'notice']

    data_object_data_adapter_mapping:
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\AdvancedManyToManyRelationAdapter:
            - "advancedManyToManyRelation"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\AdvancedManyToManyObjectRelationAdapter:
            - "advancedManyToManyObjectRelation"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\BooleanAdapter:
            - "booleanSelect"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\CalculatedValueAdapter:
            - "calculatedValue"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\CheckboxAdapter:
            - "checkbox"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\DateAdapter:
            - "date"
            - "datetime"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\DateRangeAdapter:
            - "dateRange"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\GeoBoundsAdapter:
            - "geobounds"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\GeoPointAdapter:
            - "geopoint"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\GeoPointsAdapter:
            - "geopolygon"
            - "geopolyline"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\ExternalImageAdapter:
            - "externalImage"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\HotspotImageAdapter:
            - "hotspotimage"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\ImageAdapter:
            - "image"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\ImageGalleryAdapter:
            - "imageGallery"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\LinkAdapter:
            - "link"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\ManyToManyRelationAdapter:
            - "manyToManyRelation"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\ManyToManyObjectRelationAdapter:
            - "manyToManyObjectRelation"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\ManyToOneRelationAdapter:
            - "manyToOneRelation"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\MultiSelectAdapter:
            - "countrymultiselect"
            - "languagemultiselect"
            - "multiselect"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\NumericAdapter:
            - "numeric"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\NumericRangeAdapter:
            - "numericRange"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\ReverseObjectRelationAdapter:
            - "reverseObjectRelation"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\RgbaColorAdapter:
            - "rgbaColor"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\SelectAdapter:
            - "country"
            - "gender"
            - "language"
            - "select"
            - "user"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\SliderAdapter:
            - "slider"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\StringAdapter:
            - "email"
            - "firstname"
            - "input"
            - "lastname"
            - "password"
            - "textarea"
            - "time"
            - "wysiwyg"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\StructuredTableAdapter:
            - "structuredTable"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\TableAdapter:
            - "table"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\UrlSlugAdapter:
            - "urlSlug"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\QuantityValueAdapter:
            - "quantityValue"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\InputQuantityValueAdapter:
            - "inputQuantityValue"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\QuantityValueRangeAdapter:
            - "quantityValueRange"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\VideoAdapter:
            - "video"
        Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\ConsentAdapter:
            - "consent"

mercure:
    hubs:
        studio_server:
            url: '%pimcore_studio_backend.mercure_settings.hub_url_server%'
            jwt:
                provider: 'Pimcore\Bundle\StudioBackendBundle\Mercure\Service\ServerTokenService'

        studio_client:
            url: '%pimcore_studio_backend.mercure_settings.hub_url_client%'
            jwt:
                provider: 'Pimcore\Bundle\StudioBackendBundle\Mercure\Service\ClientTokenService'