imports:
    - { resource: security.yaml }
    - { resource: firewall.yaml }
    - { resource: execution_engine.yaml }
    - { resource: doctrine.yaml }

pimcore:
    translations:
        domains:
            - studio

pimcore_studio_backend:
    open_api_scan_paths:
        - "%kernel.project_dir%/vendor/pimcore/studio-backend-bundle/src"
    asset_default_formats:
        web:
            resize_mode: "scaleByWidth"
            width: 3500
            dpi: 72
            format: "JPEG"
            quality: 85
        print:
            resize_mode: "scaleByWidth"
            width: 6000
            dpi: 300
            format: "JPEG"
            quality: 95
        office:
            resize_mode: "scaleByWidth"
            width: 1190
            dpi: 144
            format: "JPEG"
            quality: 90
    element_recycle_bin_threshold: 100
    grid:
        asset:
            predefined_columns:
                - key: preview
                  group: system
                - key: id
                  group: system
                - key: type
                  group: system
                - key: fullpath
                  group: system
                - key: filename
                  group: system
                - key: creationDate
                  group: system
                - key: modificationDate
                  group: system
                - key: size
                  group: system

mercure:
    hubs:
        studio_server:
            url: '%pimcore_studio_backend.mercure_settings.hub_url_server%'
            jwt:
                provider: 'Pimcore\Bundle\StudioBackendBundle\Mercure\Service\ServerTokenService'

        studio_client:
            url: '%pimcore_studio_backend.mercure_settings.hub_url_client%'
            jwt:
                provider: 'Pimcore\Bundle\StudioBackendBundle\Mercure\Service\ClientTokenService'