imports:
    - { resource: security.yaml }
    - { resource: firewall.yaml }

pimcore:
    translations:
        domains:
            - studio

pimcore_studio_backend:
    open_api_scan_paths:
        - "%kernel.project_dir%/vendor/pimcore/studio-backend-bundle/src"