studio_default_perspective:
  id: "studio_default_perspective"
  name: "perspective.default"
  icon: 
    type: "name"
    value: "pimcore"
  widgets_left:
    studio_document_tree_widget:
      id: "studio_document_tree_widget"
      name: "document.document-tree.title"
      widget_type: "element_tree"
      element_type: "document"
      icon:
        type: "name"
        value: "document"
      root_folder: "/"
      show_root: true
      pql: null
      page_size: null # use default page size
      classes: []
      context_permissions: [] # use all default context permissions
      is_writeable: false
    studio_asset_tree_widget:
      id: "studio_asset_tree_widget"
      name: "asset.asset-tree.title"
      widget_type: "element_tree"
      element_type: "asset"
      icon:
        type: "name"
        value: "asset"
      root_folder: "/"
      show_root: true
      pql: null
      page_size: null # use default page size
      classes: []
      context_permissions: [] # use all default context permissions
      is_writeable: false
    studio_data_object_tree_widget:
      id: "studio_data_object_tree_widget"
      name: "data-object.data-object-tree.title"
      widget_type: "element_tree"
      element_type: "data-object"
      icon:
        type: "name"
        value: "data-object"
      root_folder: "/"
      show_root: true
      pql: null
      page_size: null # use default page size
      classes: []
      context_permissions: [] # use all default context permissions
      is_writeable: false
  widgets_right: []
  widgets_bottom: []
  expanded_left: "studio_document_tree_widget"
  expanded_right: null
  context_permissions: []
  is_writeable: false
