nelmio_api_doc:
  models:
    names:
      - { alias: Asset, type: Pimcore\Bundle\StudioApiBundle\Dto\Asset }
  areas:
    path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
      - ^/studio/api(?!/doc$)
    host_patterns: # document only routes with a host of the form api.*
      - ^studio/api\.
    documentation:
      info:
        title: Studio Api
        description: It is an API platform with the rest API in the core.
        version: 0.0.1
      components:
        securitySchemes:
          access_token:
            type: http
            scheme: bearer

