nelmio_api_doc:
  models:
    names:
      - { alias: Translation, type: Pimcore\Bundle\StudioApiBundle\Dto\Translation }
  areas:
    path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
      - ^/api(?!/doc$)
    host_patterns: # document only routes with a host of the form api.*
      - ^api\.
    documentation:
      info:
        title: My API
        description: My API Description
        version: 1.0.0
