/studio/api/v1/translations:
  post:
    tags: [Translation]
    summary: Get all translations
    security:
      - access_token: []
    requestBody:
        description: Locale and array of keys
        content:
          application/json:
            schema:
               ref: '#/components/schemas/Translation'
    responses:
      '200':
        description: Successful response
        content:
          application/json:
            schema:
              ref: '#/components/schemas/Translation'
      '403':
        description: Unauthorized
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: 'Unauthorized'