name: "Codeception Tests"

on:
    # Enable Later.
    #schedule:
    #    -   cron: '0 3 * * 1,3,5'
    workflow_dispatch:
    # pull_request:
    #     branches:
    #         - "[0-9]+.[0-9]+"
    #         - "[0-9]+.x"
    #         - "feature-*"
    # push:
    #     branches:
    #         - "[0-9]+.[0-9]+"
    #         - "[0-9]+.x"

env:
    PIMCORE_PROJECT_ROOT: ${{ github.workspace }}

jobs:
    codeception-tests:
        strategy:
            matrix:
                include:
                    - {
                          php-version: 8.2,
                          database: "mariadb:10.7",
                          server_version: "10.7.7-MariaDB-1:10.7.7+maria~ubu2004",
                          dependencies: highest,
                          experimental: false,
                      }
                    - {
                          php-version: 8.2,
                          database: "mariadb:10.7",
                          server_version: "10.7.7-MariaDB-1:10.7.7+maria~ubu2004",
                          dependencies: highest,
                          pimcore_version: "11.x-dev as 11.99.9",
                          experimental: true,
                      }

        uses: pimcore/workflows-collection-public/.github/workflows/reusable-codeception-tests-centralized.yaml@codeception_workflow
        with:
            APP_ENV: test
            PIMCORE_TEST: 1
            PUBLIC_REPO: true
            PHP_VERSION: ${{ matrix.php-version }}
            DATABASE: ${{ matrix.database }}
            SERVER_VERSION: ${{ matrix.server_version }}
            DEPENDENCIES: ${{ matrix.dependencies }}
            EXPERIMENTAL: ${{ matrix.experimental }}
            PIMCORE_VERSION: ${{ matrix.pimcore_version || '' }}
