name: "PHP-CS-Fixer"

on:
    pull_request:
        branches:
            - "*"
    push:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"
            - "*_actions"
            - "feature-*"

permissions:
    contents: read

jobs:
    php-style:
        uses: pimcore/workflows-collection-public/.github/workflows/reusable-php-style.yaml@main
        with:
            head_ref: ${{ github.ref }}
            config_file: .php-cs-fixer.dist.php