name: "PHPUnit Tests"

on:
    workflow_dispatch:
    push:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"
            - "feature-*"
    pull_request:
        types: [opened, synchronize, reopened]

env:
    PIMCORE_PROJECT_ROOT: ${{ github.workspace }}

jobs:
    phpunit-tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version: [8.3, 8.4]
                dependencies: [highest]

        name: "PHPUnit tests | PHP ${{ matrix.php-version }} | ${{ matrix.dependencies }}"

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v4

            - name: "Setup PHP"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: intl, filter, zip
                  coverage: xdebug

            - name: "Install dependencies with Composer"
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependencies }}

            - name: "Run PHPUnit tests"
              run: vendor/bin/phpunit --configuration= ${{ github.workspace }}/tests/phpunit-no-coverage.xml
