name: "Trigger POEditor Translations Export"

on:
  workflow_dispatch:
  push:
    branches:
      - "[0-9]+.x"
    paths:
      - 'translations/admin.en.yaml'

permissions:
  contents: read

jobs:
  php-style:
    uses: pimcore/workflows-collection-public/.github/workflows/reusable-poeditor.yaml@main
    secrets:
      POEDITOR_ACTION_TRIGGER_TOKEN: ${{ secrets.POEDITOR_ACTION_TRIGGER_TOKEN }}