name: "Static Analysis"

on:
  schedule:
    -   cron: '0 3 * * 1,3,5'
  pull_request:
    branches:
      - "[0-9]+.[0-9]+"
      - "[0-9]+.x"
      - "feature-*"
    paths-ignore:
      #- 'doc/**'
      - 'public/**'
  push:
    branches:
      - "[0-9]+.[0-9]+"
      - "[0-9]+.x"
      - "*_actions"

jobs:
  static-analysis:
    uses: pimcore/workflows-collection-public/.github/workflows/reusable-static-analysis-8-2-only-public.yaml@main